INSERT INTO CINEMA (ADRESS, CITY, NAME, POSTAL_CODE) VALUES
('Major,15', 'Tarragona', '' , 43100);

INSERT INTO CINEMA (ADRESS, CITY, NAME, POSTAL_CODE) VALUES
('Major,30', 'Tarragona', '' , 43100);

INSERT INTO CINEMA (ADRESS, CITY, NAME, POSTAL_CODE) VALUES
('Major,40', 'Tarragona', '' , 43100);